### ISSUE TITLE
Option "Auto import domain classes" not working

### ISSUE THREAD

**Issue by joasgarcia** [sheehan/grails-console#25]
I am using domain class without import them e take the error below. Can you help me?

![error](https://cloud.githubusercontent.com/assets/6011412/6139010/135d8612-b16e-11e4-8744-7b4d2323d401.PNG)

**Comment by sheehan** [comment]
Strange. Does your class show up in the list if you run this in the console?

```groovy
grailsApplication.domainClasses*.fullName
```

**Comment by dpalita** [comment]
Same here, using grails 2.3.4 and console plugin 1.5.3
The different domain classes I tested do show up when I run your code snippet in the console...

**Comment by sheehan** [comment]
Found the issue, thanks. This should be fixed now in 1.5.4.

**Comment by joasgarcia** [comment]
Thanks @sheehan. When the 1.5.4 version will be published?

**Comment by sheehan** [comment]
1.5.4 should be available now. For some reason the plugin page hasn't updated yet.
