### ISSUE TITLE
Using the console over HTTPS results to blocked requests

### ISSUE THREAD

**Issue by jlehva** [sheehan/grails-console#26]
I am trying to use the plugin on my server over https (with a self signed certificate, if that matters). The commands are not being executed properly. Chromes console shows the following error:

```
Mixed Content: The page at 'https://example.com/console#new' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.com/console/execute'. This request has been blocked; the content must be served over HTTPS.
```

So it seems the console is trying to POST to url starting with "http" instead of "https" and the request gets blocked.

Is this a known issue or am I just doing something wrong?

**Comment by sheehan** [comment]
That should be coming from the `grails.serverURL` setting. Do you have that set to an https url?

**Comment by jlehva** [comment]
Actually I didn't have the grails.serverURL set up at all yet. So I was doing something wrong after all. Thank you very much for your help and quick response. :) :+1:
