### ISSUE TITLE
Support Grails 3

### ISSUE THREAD

**Issue by zyro23** [sheehan/grails-console#28]
given Grails-3.0.0 just reached M2 and a final is planned to be released soon, it would be nice to see this plugin work with Grails 3 :)

thanks, zyro

**Comment by sheehan** [comment]
done!

https://bintray.com/sheehan/grails-plugins/org.grails.plugins%3Aconsole/view

**Comment by zyro23** [comment]
awesome. if not happened already you might want to link it to https://bintray.com/grails/plugins as well. thanks! zyro
