### ISSUE TITLE
Better configuration of editor tabs and indentation

### ISSUE THREAD

**Issue by tobia** [sheehan/grails-console#29]
I just overrode `views/console/index.gsp` in my app so that I could add the following settings after `<con:js/>` but before `App.start()`:

	CodeMirror.defaults.indentWithTabs = true;
	CodeMirror.defaults.indentUnit = 4;

CodeMirror's default settings have a tab size of 4, indent size of 2, and indent with spaces, which I don't think make much sense.

Maybe the Console plugin could provide some sensible defaults (is there an official style guide for Groovy code?) or better yet some configurability.

**Comment by sheehan** [comment]
good idea! i'll take a look when i get a sec

**Comment by sheehan** [comment]
In the latest version I changed the indent size to 4, but I still want to look at adding configurability to these options.

**Comment by AleCaste** [comment]
That would be wonderful. This is the only thing I am really missing in this plugin.
This will allow us to just copy+paste the code we write on the console in our project as we use a specific tab indentation configuration.
By the way this is the MOST USEFUL plugin I have ever installed!!!!! One of our project is really big and this plugin allows us to cut the number of restarts and try a bunch of different things before adding final code to the project.
It is a gem! Honestly. Very well done.

**Comment by sheehan** [comment]
@AleCaste thanks!. I just pushed a new version with these config options. See https://github.com/sheehan/grails-console/blob/master/README.md#configuration
