### ISSUE TITLE
Disable Ctrl+left to show local storage

### ISSUE THREAD

**Issue by igorrosenberg** [sheehan/grails-console#31]
*Setup*
compile ":console:1.5.2"
Firefox 37.0.1 on Windows. 

*Problem*
The ctrl-left shortcut is mapped to displaying the local storage pane.
This is very disturbing while editing code, as this shortcut is usually used to move one word left.

*Solution*
Is it possible to disable the ctrl-left shortcut mapped to localstorage ?

**Comment by sheehan** [comment]
Never noticed that. I'll fix it in the next release, thanks.
