### ISSUE TITLE
Unable to obtain dependency

### ISSUE THREAD

**Issue by syeds-git** [sheehan/grails-console#34]
I am trying to include this plugin but so far I am unable to do so. I am getting following exception:

    Resolve error obtaining dependencies: Could not find artifact org.grails.plugins:grails-console:jar:1.5.5 in grailsCentral (http://repo.grails.org/grails/plugins) 

I have following code in my BuildConfig.groovy

        dependencies {
		compile(
				'org.grails.plugins:grails-console:1.5.5'
                  ...)

I have also tried using *compile ":console:1.5.5"*

and following repos

    repositories {
        inherits true
        grailsPlugins()
        grailsHome()
        mavenLocal()
        grailsCentral()
        mavenCentral()
    }

I am using Grails 2.4.3 with GGTS Version: 3.6.1.RELEASE

**Comment by sheehan** [comment]
The plugin should go in the `plugins` block like:

```groovy
grails.project.dependency.resolution = {
  repositories {
    // ...
  }
  dependencies {
    // ...
  }
  plugins {
    runtime ':console:1.5.5'
    // ...
  }
}
```

**Comment by syeds-git** [comment]
Thanks, it works now

**Comment by sheehan** [comment]
:+1:

**Comment by syeds-git** [comment]
It may be obvious to more experienced grails users but for people like me it would be useful to have this info in the readme. Thanks

**Comment by sheehan** [comment]
no problem. its updated now
