### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by jglapa** [sheehan/grails-console#36]
I'm getting the following exception when submitting an execute operation
console v1.5.4
Grails v2.4.5

The app is deployed on Tomcat with Nginx acting as SSL Proxy.
I suspect that the scheme is established on server side and it's http over there?

![image](https://cloud.githubusercontent.com/assets/742104/8478691/4571d4f8-20d3-11e5-98a6-5e81f63ab293.png)

**Comment by sheehan** [comment]
Have you set grails.serverURL? See #26

**Comment by jglapa** [comment]
Yes, problably that's the problem I dont' have `grails.serverURL` property set.
I don't really want to set it because my app is deployed on different domains, That would make my life complicated in terms of configuration.

Wouldn't it be easier to provide a protocol relative URL on client side?
Something like:
```
'//'+ document.domain + '/console/execute'
```

This should work in all cases?

**Comment by sheehan** [comment]
That won't work if the application has a context path. I can probably check the `window.location.protocol` though and make sure we're using the same one. I'll take a look.

**Comment by jglapa** [comment]
you can check for contextPath in request object:
`'//'+ document.domain + ${request.contextPath ?:'/'} + 'console/execute'`
altough if it's behind a reverse proxy that hides the context path it will be no use

**Comment by sheehan** [comment]
@jglapa this should be fixed now in the latest. See https://github.com/sheehan/grails-console/blob/e5e92cb2c6b2edc68d5a49b5d741e2198997979a/web/app/app.coffee#L12
