### ISSUE TITLE
Error on console/index page

### ISSUE THREAD

**Issue by bavicj** [sheehan/grails-console#37]
Hi,

I created vanilla grails 3.0.4 app, installed console plugin as described in README (runtime 'org.grails.plugins:grails-console:2.0.2') but when I ran app and navigate to /console I got this error:

<img width="1431" alt="screen shot 2015-07-30 at 00 51 44" src="https://cloud.githubusercontent.com/assets/3510699/8971903/2f3e9d82-3655-11e5-9a17-da89b5d41846.png">

**Comment by sheehan** [comment]
It looks like this is a bug in grails 3.0.4: https://github.com/grails/grails-core/issues/9145

**Comment by sheehan** [comment]
It looks like it should work now with the latest asset-pipeline (3.0.6).
