### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by walshe** [sheehan/grails-console#39]
having issues using the plugin with a grails 2.4.4 app, I think its something to do with the Spring security rest plugin i am also using

![screen shot 2015-08-09 at 16 31 46](https://cloud.githubusercontent.com/assets/231136/9155584/2cbd0820-3eb4-11e5-90fd-46d507704a70.png)

**Comment by sheehan** [comment]
I think this has to do with your spring security configuration. There's some info here: https://grails-plugins.github.io/grails-spring-security-core/guide/requestMappings.html
