### ISSUE TITLE
GroovyPageView: [views/console/index.gsp:9] Error executing tag <g:render>: No such property: AssetPipelineConfigHolder for class: asset.pipeline.grails.CachingLinkGenerator

### ISSUE THREAD

**Issue by VenelinPetkov** [sheehan/grails-console#42]
Issue with grails 3.0.4

    Line | Method
->>    9 | createGroovyPageException    in /WEB-INF/grails-app/views/console/index.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by GrailsTagException: [views/console/index.gsp:9] Error executing tag <g:render>: No such property: AssetPipelineConfigHolder for class: asset.pipeline.grails.CachingLinkGenerator
->>    9 | doCall                       in views/console/index.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by MissingPropertyException: No such property: AssetPipelineConfigHolder for class: asset.pipeline.grails.CachingLinkGenerator
->>   32 | asset                        in asset.pipeline.grails.CachingLinkGenerator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     18 | resource                     in     ''
|     15 | run . . . . . . . . . . . .  in gsp_grails_console_console_favicon_gsp
|     27 | doCall                       in gsp_grails_console_consoleindex_gsp$_run_closure1
|     34 | run . . . . . . . . . . . .  in gsp_grails_console_consoleindex_gsp
|     62 | doFilter                     in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|     53 | doFilter . . . . . . . . . . in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     62 | doFilter                     in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|   1142 | runWorker . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    617 | run                          in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . . . .  in java.lang.Thread

**Comment by sheehan** [comment]
This is caused by an error in the asset-pipeline plugin v3.0.5. It works if you upgrade asset-pipeline to 3.0.6 or higher in build.gradle.
