### ISSUE TITLE
Main page fetches resources from address serverUrl/console-2.0.2/** instead of serverUrl/console

### ISSUE THREAD

**Issue by droggo** [sheehan/grails-console#45]
When we open /console page, all additional resources are fetched from path /console-2.0.2 instead of /console. for example `http://localhost:8080/console-2.0.2/release/app.js` . When application also uses security like spring-security, this address needs to be additionally opened. Is this intended?

It happens on:
Grails 3.1.0.RC1
Console Plugin 2.0.3

**Comment by droggo** [comment]
One more thing - plugin version is 2.0.3 but address used is console-2.0.2

**Comment by sheehan** [comment]
I've update this for 2.0.4. All resources are now under `/console`
