### ISSUE TITLE
Console broken in grails 3.1.0.RC2 and 3.0.12 because of new URL for static resources

### ISSUE THREAD

**Issue by droggo** [sheehan/grails-console#47]
Please check https://github.com/grails/grails-core/releases/tag/v3.0.12
Static resources were moved from default `/**` to `/static/**` URL and console cannot resolve them.

Workaround using config option `grails.resources.pattern = '/**'` works for this problem.

**Comment by sheehan** [comment]
Thanks. Seems to be caused by https://github.com/grails/grails-core/issues/9584

I'll update the readme with a note.

**Comment by sheehan** [comment]
The related issue was fixed
