### ISSUE TITLE
database commands fail if dataSource is defined with logSql=true

### ISSUE THREAD

**Issue by tircnf** [sheehan/grails-console#51]
with grails 3.1.8, and console plugin version 2.0.5, if you execute a database command you get the following error if you have logSql set to true in your dataSource.

> groovy.lang.MissingMethodException: No signature of method: org.grails.plugins.console.ConsoleService$_createInterceptor_closure1.doCall() is applicable for argument types: (java.lang.Integer, java.lang.String) values: [0, Hibernate: select this_.id as id1_0_0_, this_.version as version2_0_0_, this_.first_name as first_na3_0_0_, this_.last_name as last_nam4_0_0_ from foo this_]
> Possible solutions: doCall(java.lang.String), findAll(), findAll()
> at java.io.PrintStream.write(PrintStream.java:480)
> at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
> at java.io.PrintStream.write(PrintStream.java:527)
> at java.io.PrintStream.print(PrintStream.java:669)
> at java.io.PrintStream.println(PrintStream.java:806)
> at Script1.run(Script1.groovy:1)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> 

To reproduce:

grails create-app testapp
grails create-domain-class foo

    class Foo {

        static constraints = {
        }

        String lastName;
        String firstName;
    }

modify your application.yml file to turn on sql logging.

    <snip>
    environments:
        development:
            dataSource:
                dbCreate: create-drop
                url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
                logSql: true
    <snip>

Run your app, navigate to http://localhost:8080/console and try to execute "Foo.list()"  or "Foo.count()"

**Comment by sheehan** [comment]
Thanks for the report. Fixed in v2.0.6.
