### ISSUE TITLE
enabling in production in later releases doesn't seem to work

### ISSUE THREAD

**Issue by gschrader** [sheehan/grails-console#56]
I'm trying the latest version 2.0.8.

I have `grails.plugin.console.enabled = true` in my `Config.groovy`, I set a breakpoint in EnabledInterceptor and `consoleConfig.enabled` ends up being false.

I guessed maybe it had something do with 2b2b2151a1712ed5fd0b74a2a43904d8bce4c6f7 so
I tried an earlier version 2.0.4 and it seems to work.

**Comment by sheehan** [comment]
Which version of Grails are you using? `Config.groovy` should only by for Grails 2.x.

**Comment by gschrader** [comment]
Oops my bad, I had both `Config.groovy` and `application.groovy` while I upgraded from 2 to 3. Thanks for setting me straight, It's working correctly for me now!
