### ISSUE TITLE
Console view not rendering properly

### ISSUE THREAD

**Issue by ilmoralito** [sheehan/grails-console#57]
Hi. I installed console plugin to a grails 3.2 app when i go to console i get the following render problems

![nami](https://cloud.githubusercontent.com/assets/928920/19329597/d07643d4-9096-11e6-8d9d-98e86fa5c205.png)

The plugin is working fine but not rendering properly. The only plugin i am using with console its spring security core. This area the static rules i am using to get access as admin

    [pattern: '/console/**',     access: ['ROLE_ADMIN']],
    [pattern: '/plugins/console*/**', access: ['ROLE_ADMIN']]

Thanks for your time

**Comment by sheehan** [comment]
Can you check the browser devtools and see which resources are failing to load? Might need a different pattern.

**Comment by jphiloon** [comment]
You need to allow access for /static/console/**

**Comment by sheehan** [comment]
Thanks @jphiloon. I've updated the readme.
