### ISSUE TITLE
Add a package name to `ConsoleUrlMappings`

### ISSUE THREAD

**Issue by jjchiw** [sheehan/grails-console#59]
Hi

I'm trying to get rid off all the `WARN` messages when grails is booting and I found this one

```
ERROR --- [           main] g.boot.config.tools.ClassPathScanner     : The application defines a Groovy source using the default package. Please move all Groovy sources into a package.
```

Then to verify which Groovy sources is using the default package I ran in the Console

```
ctx.grailsApplication.allClasses.findAll { !it.getPackage() }*.name
```

And this was the result

```
['DefaultCacheConfig', 'ConsoleUrlMappings']
```

So I came here searched for [`ConsoleUrlMappings`](https://github.com/sheehan/grails-console/blob/1edba78770d709b8117dffcce339d1486a3474cf/grails3/plugin/grails-app/controllers/ConsoleUrlMappings.groovy) and as `ClassPathScanner` `ConsoleUrlMappings` is not in a package....

I'm using:
```
| Grails Version: 3.2.4
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_112
| grails-console Version: 2.0.8
```

Thanks :)

**Comment by sheehan** [comment]
fixed in the latest version
