### ISSUE TITLE
Ability to disable console in config

### ISSUE THREAD

**Issue by ianpgall** [sheehan/grails-console#6]
Is there currently a way to disable the console in the app's config? Most plugins/features have the ability to set an "enabled" property to true/false. This is helpful for configuring based on an environment. For example, I don't want this to be available in production, but definitely for development. I haven't been able to disable it using random things I could think of to put in config, and I don't see it documented anywhere. Is it possible to make it available?

**Comment by gantaa** [comment]
I'm running a war in stage and production and I'm getting a 404 when trying to access the console (it works perfectly in localhost).  A war hosted in tomcat, there are no errors in the catalina logs.  I have set 
```grails.plugin.console.enabled = true``` 
in Config.groovy.  I've tried both with the config value in an environment blocks, and with it as a global config.  I want the console enabled in all environments and it is secured and working in localhost with the shiro plugin.   I will be upgrading to Grails 3 this year, but for now I need to be on 2.3.11

What is the best way to debug or troubleshoot this?
