### ISSUE TITLE
Result is not displayed with Grails 3.3.0.RC1

### ISSUE THREAD

**Issue by codeconsole** [sheehan/grails-console#62]
If you view the network tab, you can see that the result is correctly sent back to the browser, but it does not appear.

All that shows up is the ≫ character.
If you inspect the DOM where the result should be, the element is empty.

**Comment by sheehan** [comment]
It looks like the response is returning Content-Type: `text/html` where it should be `application/json`.

**Comment by sheehan** [comment]
I filed an issue in grails-core for this https://github.com/grails/grails-core/issues/10745

**Comment by codeconsole** [comment]
So it sounds like 3.2.x plugins are not compatible with 3.3.x plugins

**Comment by sheehan** [comment]
I can't imagine that that's on purpose, but who knows. I started updating this plugin to 3.3 and will release a new version once I get a chance to finish it up.

**Comment by kastork** [comment]
This issue remains in the 3.3.0 release of grails.

**Comment by sheehan** [comment]
Should work now in v2.1.0

**Comment by LuisMuniz** [comment]
Can you please update your plugin page. I just went through the whole debugging an diagnosing all over again, because this issue was closed and the plugin page still points to version 2.0.9 :( not cool
