### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ilsasdo** [sheehan/grails-console#65]
Hi, I love this plugin, but I noticed that the version published (2.10) is compiled with java8 raising an "Unsupported major.minor version 52.0" exception when running the application.

Can you please publish the plugin with java 7 compatibility?

Thank you,

Enrico

**Comment by sheehan** [comment]
Thanks! Try 2.11 and let me know if that doesn't work.

**Comment by ilsasdo** [comment]
Great! It works, thank you!
