### ISSUE TITLE
Grails 3.3.1 & Console 2.1.1 - Content Type of script responses is text/html - and UI is blank

### ISSUE THREAD

**Issue by jlamber4** [sheehan/grails-console#66]
Seems to be a regression from #62 in Grails 3.3.1. I tried using both version 2.1.0 and 2.1.1 of the console plugin but the response coming back from the server has incorrect content type - which causes the console UI to show only ">>"

**Comment by sheehan** [comment]
That's strange. I just tested a fresh 3.3.1 app with console 2.1.1 and it worked for me. Is it possible that you have multiple versions declared or something like that?

**Comment by jlamber4** [comment]
I guess that was the case, but its wasnt obvious how. According to intellij's gradle analysis I only have 2.1.1 in my classpath, I've done cleans and restarts too. My grails project is old, its been upgraded through all the versions since Grails 3.0, and I just upgraded to 3.3.1 yesterday. 

But after another round of clean, sync grale project, clean, change version, clean (etc. etc.) It seems to have flushed whatever old stuff away and is working now!
