### ISSUE TITLE
No longer getting log.info trace statements in console output

### ISSUE THREAD

**Issue by gantaa** [sheehan/grails-console#69]
We upgraded our project from Grails 2.3.11 to the latest Grails 3.3.8.  Both projects use the Grails console.  When I run service methods in our Grails 2 codebase from grails console, I am able to see STDOUT logs when my Grails services runs log.info()

However, in Grails 3 with the latest console plugin, none of our logging statements make it to the console's standard output.  println statements do make it, but my services do not use this.  Do I need to add a specific configuration to logback.groovy to get these log statements back in console plugin?  These log statements work when running my app, so, my logging config feels identical to the old one, but I may have missed something in the migration...

**Comment by sheehan** [comment]
It should work the same way. The plugin just intercepts System.out. Maybe you need to specify in logback.groovy to send trace logs to STDOUT?

**Comment by gantaa** [comment]
Confirmed this was indeed a missing configuration in logback.  My apologies
